/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Silverado.glb 
*/

import React, { useRef } from 'react'
import { useSnapshot } from "valtio"

import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';


export function Silverado(props) {
  const { nodes, materials } = useGLTF('models/Silverado.glb')
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)

  const canvasRef = useRef(document.createElement("canvas"));
  const textureRef = useRef();
  const context = useRef(canvasRef.current.getContext("2d"));
console.log()

  canvasRef.current.width = 1600;
  canvasRef.current.height = 1600;

  let ctx = context.current;

  ctx.globalCompositeOperation = "hue";

  const img = document.getElementById(`overlay${overlay}`);

  if (img.complete) {
    ctx.drawImage(img, 0, 0);
    if (snap1.base.BaseMtl !== "none") {
      if(overlay!==1){
      ctx.fillStyle = snap1.base.BaseMtl;
      ctx.fillRect(0, 0, 1600, 1600);
      }
    }


    if (textureRef.current) {
      textureRef.current.needsUpdate = true;
    }
  }

  else {
    img.onload = function () {
      ctx.drawImage(img, 0, 0);
      if (snap1.base.BaseMtl !== "none") {
        if(overlay!==1){
        ctx.fillStyle = snap1.base.BaseMtl;
        ctx.fillRect(0, 0, 1600, 1600);
        }
      }
      


      if (textureRef.current) {
        textureRef.current.needsUpdate = true;
      }
    }
  }
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body.geometry}>
        <meshStandardMaterial {...materials.BaseMtl} color={overlay==1 || overlay==13 ? (snap1.base.BaseMtl!=="none" ? snap1.base.BaseMtl : 0xffffff) : 0xffffff}>
          <canvasTexture
            flipY={false}
            wrapS={1000}
            wrapT={1000}
            colorSpace='srgb'
            ref={textureRef}
            attach="map"
            image={canvasRef.current}
          />
        </meshStandardMaterial>
      </mesh>
      <mesh geometry={nodes.Object_10.geometry} material={materials.refl_black} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.refl_black} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.refl_black} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.refl_black} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.refl_black} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.refl_black} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_2.geometry} material={materials.GlassRed} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.refl_black} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.refl_black} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.refl_black} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.tires} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.Red_Light} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.mirror} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.black} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.orange} />
      <mesh geometry={nodes.Object_69.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['04___Default']} />
      <mesh geometry={nodes.Object_70.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Object_71.geometry} material={materials.brake} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.brake} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.brake} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.brake} />
      <mesh geometry={nodes.Object_75.geometry} material={materials.brake} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.brake} />
      <mesh geometry={nodes.Object_77.geometry} material={materials.brake} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.brake} />
      <mesh geometry={nodes.Object_79.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Iron_Clean_Distorted} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Object_81.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Object_83.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Object_85.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Object_87.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Object_89.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.refl_black} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.chrome} />
      <mesh geometry={nodes.Object_91.geometry} material={materials.glasss} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.glasss} />
      <mesh geometry={nodes.Object_93.geometry} material={materials.glasss} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_95.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.white_Light223} />
    </group>
  )
}

useGLTF.preload('/Silverado.glb')
